
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author (Milton Jesús Vera Contreras - miltonjesusvc@ufps.edu.co)
 * @version 0.000000000000001 :) --> Math.sin(Math.PI-Double.MIN_VALUE)
 */
public class MainSandwichMachineView extends javax.swing.JFrame {

    /**
     * Creates new form CoffeeMachineView
     */
    public MainSandwichMachineView() {
        initComponents();
        center();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        lblPrecioCompraQueso = new javax.swing.JLabel();
        txtPrecioCompraQueso = new javax.swing.JTextField();
        lblPrecioCompraMortadela = new javax.swing.JLabel();
        txtPrecioCompraMortadela = new javax.swing.JTextField();
        lblPrecioCompraJamon = new javax.swing.JLabel();
        txtPrecioCompraJamon = new javax.swing.JTextField();
        lblPrecioCompraPanBanco = new javax.swing.JLabel();
        txtPrecioCompraPanBlanco = new javax.swing.JTextField();
        lblPrecioCompraPanIntegral = new javax.swing.JLabel();
        txtPrecioCompraPanIntegral = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        cmdInicializarMaquina = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sandwich Vending Machine");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        setResizable(false);

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandwich-machine.png"))); // NOI18N
        lblImagen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblImagen, java.awt.BorderLayout.EAST);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.setLayout(new java.awt.GridLayout(1, 3));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motilon-brand.png"))); // NOI18N
        lblTitulo.setToolTipText("");
        panelMenu.add(lblTitulo);

        getContentPane().add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new java.awt.GridLayout(5, 2));

        lblPrecioCompraQueso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecioCompraQueso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioCompraQueso.setText("Precio Compra 1 gramo de Queso $$$:");
        lblPrecioCompraQueso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPrecioCompraQueso);

        txtPrecioCompraQueso.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPrecioCompraQueso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioCompraQueso.setText("0");
        txtPrecioCompraQueso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioCompraQueso.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelDatos.add(txtPrecioCompraQueso);

        lblPrecioCompraMortadela.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecioCompraMortadela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioCompraMortadela.setText("Precio Compra 1 gramo de Mortadela $$$:");
        lblPrecioCompraMortadela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPrecioCompraMortadela);

        txtPrecioCompraMortadela.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPrecioCompraMortadela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioCompraMortadela.setText("0");
        txtPrecioCompraMortadela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioCompraMortadela.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelDatos.add(txtPrecioCompraMortadela);

        lblPrecioCompraJamon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecioCompraJamon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioCompraJamon.setText("Precio Compra 1 gramo de Jamón $$$:");
        lblPrecioCompraJamon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPrecioCompraJamon);

        txtPrecioCompraJamon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPrecioCompraJamon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioCompraJamon.setText("0");
        txtPrecioCompraJamon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioCompraJamon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelDatos.add(txtPrecioCompraJamon);

        lblPrecioCompraPanBanco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecioCompraPanBanco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioCompraPanBanco.setText("Precio Compra 1 tajada de Pan Blanco $$$:");
        lblPrecioCompraPanBanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPrecioCompraPanBanco);

        txtPrecioCompraPanBlanco.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPrecioCompraPanBlanco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioCompraPanBlanco.setText("0");
        txtPrecioCompraPanBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioCompraPanBlanco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelDatos.add(txtPrecioCompraPanBlanco);

        lblPrecioCompraPanIntegral.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecioCompraPanIntegral.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioCompraPanIntegral.setText("Precio Compra 1 tajada de Pan Integral $$$:");
        lblPrecioCompraPanIntegral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPrecioCompraPanIntegral);

        txtPrecioCompraPanIntegral.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtPrecioCompraPanIntegral.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecioCompraPanIntegral.setText("0");
        txtPrecioCompraPanIntegral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPrecioCompraPanIntegral.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelDatos.add(txtPrecioCompraPanIntegral);

        getContentPane().add(panelDatos, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.setLayout(new java.awt.GridLayout(1, 2));

        cmdInicializarMaquina.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdInicializarMaquina.setText("Inicializar Máquina");
        cmdInicializarMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdInicializarMaquinaActionPerformed(evt);
            }
        });
        panelBotones.add(cmdInicializarMaquina);

        cmdSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdSalir.setText("Salir...");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        panelBotones.add(cmdSalir);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdInicializarMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdInicializarMaquinaActionPerformed
        inicializarMaquina();
        this.dispose();
    }//GEN-LAST:event_cmdInicializarMaquinaActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SandwichMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SandwichMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SandwichMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SandwichMachineView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSandwichMachineView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdInicializarMaquina;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPrecioCompraJamon;
    private javax.swing.JLabel lblPrecioCompraMortadela;
    private javax.swing.JLabel lblPrecioCompraPanBanco;
    private javax.swing.JLabel lblPrecioCompraPanIntegral;
    private javax.swing.JLabel lblPrecioCompraQueso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtPrecioCompraJamon;
    private javax.swing.JTextField txtPrecioCompraMortadela;
    private javax.swing.JTextField txtPrecioCompraPanBlanco;
    private javax.swing.JTextField txtPrecioCompraPanIntegral;
    private javax.swing.JTextField txtPrecioCompraQueso;
    // End of variables declaration//GEN-END:variables

    private void inicializarMaquina() {
        int precioCompraQueso = Integer.parseInt(txtPrecioCompraQueso.getText());
        int precioCompraMortadela = Integer.parseInt(txtPrecioCompraMortadela.getText());
        int precioCompraJamon = Integer.parseInt(txtPrecioCompraJamon.getText());
        int precioCompraPanBlanco = Integer.parseInt(txtPrecioCompraPanBlanco.getText());
        int precioCompraPanIntegral = Integer.parseInt(txtPrecioCompraPanIntegral.getText());

        this.setVisible(false);
        new SandwichMachineView(precioCompraQueso, precioCompraMortadela, precioCompraJamon, precioCompraPanBlanco, precioCompraPanIntegral).setVisible(true);
    }

    private void center() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
}
