
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.GridLayout;
import java.awt.Toolkit;
import javax.swing.WindowConstants;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author (Milton Jesús Vera Contreras - miltonjesusvc@ufps.edu.co)
 * @version 0.000000000000001 :) --> Math.sin(Math.PI-Double.MIN_VALUE)
 */
public class SandwichMachineView extends javax.swing.JFrame {

    protected MaquinaSandwich maquina;

    /**
     * Creates new form CoffeeMachineView
     */
    public SandwichMachineView(int precioCompraQueso, int precioCompraMortadela, int precioCompraJamon, int precioCompraPanBlanco, int precioCompraPanIntegral) {
        maquina = new MaquinaSandwich(precioCompraQueso, precioCompraMortadela, precioCompraJamon, precioCompraPanBlanco, precioCompraPanIntegral);
        initComponents();
        center();
        actualizarGUI();
        comboTipoSandwich.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagen = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        lblQueso = new javax.swing.JLabel();
        txtQueso = new javax.swing.JTextField();
        lblMortadela = new javax.swing.JLabel();
        txtMortadela = new javax.swing.JTextField();
        lblJamon = new javax.swing.JLabel();
        txtJamon = new javax.swing.JTextField();
        lblPanBanco = new javax.swing.JLabel();
        txtPanBlanco = new javax.swing.JTextField();
        lblPanIntegral = new javax.swing.JLabel();
        txtPanIntegral = new javax.swing.JTextField();
        lblIngresos = new javax.swing.JLabel();
        txtIngresos = new javax.swing.JTextField();
        lblIVA = new javax.swing.JLabel();
        txtIVA = new javax.swing.JTextField();
        lblCostosFijos = new javax.swing.JLabel();
        txtCostosFijos = new javax.swing.JTextField();
        lblRiesgos = new javax.swing.JLabel();
        txtRiesgos = new javax.swing.JTextField();
        lblGananciasNetas = new javax.swing.JLabel();
        txtGananciasNetas = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        lblListaTiposSandwich = new javax.swing.JLabel();
        comboTipoSandwich = new javax.swing.JComboBox<>();
        lblListaTipoPan = new javax.swing.JLabel();
        comboTipoPan = new javax.swing.JComboBox<>();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cmdRegistrarVenta = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sandwich Vending Machine");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        setResizable(false);

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandwich-machine.png"))); // NOI18N
        lblImagen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblImagen, java.awt.BorderLayout.EAST);

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu.setLayout(new java.awt.GridLayout(1, 3));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/motilon-brand.png"))); // NOI18N
        lblTitulo.setToolTipText("");
        panelMenu.add(lblTitulo);

        getContentPane().add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new java.awt.GridLayout(10, 2));

        lblQueso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblQueso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblQueso.setText("Cantidad de Queso (gramos):");
        lblQueso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblQueso);

        txtQueso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtQueso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQueso.setText("0");
        txtQueso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtQueso.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtQueso.setEnabled(false);
        panelDatos.add(txtQueso);

        lblMortadela.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMortadela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMortadela.setText("Cantidad de Mortadela (gramos):");
        lblMortadela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblMortadela);

        txtMortadela.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMortadela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtMortadela.setText("0");
        txtMortadela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMortadela.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMortadela.setEnabled(false);
        panelDatos.add(txtMortadela);

        lblJamon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblJamon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJamon.setText("Cantidad de Jamón (gramos):");
        lblJamon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblJamon);

        txtJamon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtJamon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJamon.setText("0");
        txtJamon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtJamon.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtJamon.setEnabled(false);
        panelDatos.add(txtJamon);

        lblPanBanco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPanBanco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPanBanco.setText("Cantidad de Pan Blanco (unidad):");
        lblPanBanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPanBanco);

        txtPanBlanco.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPanBlanco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPanBlanco.setText("0");
        txtPanBlanco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPanBlanco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPanBlanco.setEnabled(false);
        panelDatos.add(txtPanBlanco);

        lblPanIntegral.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPanIntegral.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPanIntegral.setText("Cantidad de Pan Integral (unidad):");
        lblPanIntegral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblPanIntegral);

        txtPanIntegral.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPanIntegral.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPanIntegral.setText("0");
        txtPanIntegral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPanIntegral.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPanIntegral.setEnabled(false);
        panelDatos.add(txtPanIntegral);

        lblIngresos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblIngresos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIngresos.setText("Ingresos por Ventas $$$:");
        lblIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblIngresos);

        txtIngresos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtIngresos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIngresos.setText("0");
        txtIngresos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIngresos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIngresos.setEnabled(false);
        panelDatos.add(txtIngresos);

        lblIVA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblIVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIVA.setText("IVA 19% $$$:");
        lblIVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblIVA);

        txtIVA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtIVA.setText("0");
        txtIVA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIVA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIVA.setEnabled(false);
        panelDatos.add(txtIVA);

        lblCostosFijos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCostosFijos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCostosFijos.setText("Reserva Costos Fijos 5% $$$:");
        lblCostosFijos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblCostosFijos);

        txtCostosFijos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCostosFijos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCostosFijos.setText("0");
        txtCostosFijos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCostosFijos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCostosFijos.setEnabled(false);
        panelDatos.add(txtCostosFijos);

        lblRiesgos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRiesgos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRiesgos.setText("Reserva Riesgos 1% $$$:");
        lblRiesgos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblRiesgos);

        txtRiesgos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtRiesgos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRiesgos.setText("0");
        txtRiesgos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtRiesgos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtRiesgos.setEnabled(false);
        panelDatos.add(txtRiesgos);

        lblGananciasNetas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblGananciasNetas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGananciasNetas.setText("Ganancias Netas 10% $$$:");
        lblGananciasNetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDatos.add(lblGananciasNetas);

        txtGananciasNetas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtGananciasNetas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGananciasNetas.setText("0");
        txtGananciasNetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtGananciasNetas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGananciasNetas.setEnabled(false);
        panelDatos.add(txtGananciasNetas);

        getContentPane().add(panelDatos, java.awt.BorderLayout.CENTER);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.setLayout(new java.awt.GridLayout(4, 2));

        lblListaTiposSandwich.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblListaTiposSandwich.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblListaTiposSandwich.setText("Tipo de Sandwich:");
        lblListaTiposSandwich.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(lblListaTiposSandwich);

        comboTipoSandwich.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboTipoSandwich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-Medio Simple", "2-Medio Exquisito", "3-Normal Simple", "4-Normal Exquisito", "5-Doble Normal", "6-Doble Exquisito" }));
        comboTipoSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoSandwichActionPerformed(evt);
            }
        });
        panelBotones.add(comboTipoSandwich);

        lblListaTipoPan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblListaTipoPan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblListaTipoPan.setText("Tipo de Pan:");
        lblListaTipoPan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(lblListaTipoPan);

        comboTipoPan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comboTipoPan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1-Pan Blanco", "2-Pan Integral" }));
        comboTipoPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPanActionPerformed(evt);
            }
        });
        panelBotones.add(comboTipoPan);

        lblPrecio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecio.setText("Precio $$$:");
        lblPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.add(lblPrecio);

        txtPrecio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPrecio.setText("0");
        txtPrecio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecio.setEnabled(false);
        panelBotones.add(txtPrecio);

        cmdRegistrarVenta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdRegistrarVenta.setText("Registrar Venta");
        cmdRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistrarVentaActionPerformed(evt);
            }
        });
        panelBotones.add(cmdRegistrarVenta);

        cmdSalir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmdSalir.setText("Apagar la Máquina...");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        panelBotones.add(cmdSalir);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoSandwichActionPerformed
        int precio = maquina.calcularPrecioVenta(comboTipoSandwich.getSelectedIndex() + 1, comboTipoPan.getSelectedIndex() + 1);
        txtPrecio.setText(String.valueOf(precio));
    }//GEN-LAST:event_comboTipoSandwichActionPerformed

    private void cmdRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarVentaActionPerformed
        if(!maquina.registrarVenta(comboTipoSandwich.getSelectedIndex() + 1, comboTipoPan.getSelectedIndex() + 1))
        {
            JOptionPane.showMessageDialog(this, "Ingredientes Insuficientes", "Sandwich Machine Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
         actualizarGUI();
         JOptionPane.showMessageDialog(this, "Venta Exitosa", "Sandwich Machine Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cmdRegistrarVentaActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void comboTipoPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPanActionPerformed
        int precio = maquina.calcularPrecioVenta(comboTipoSandwich.getSelectedIndex() + 1, comboTipoPan.getSelectedIndex() + 1);
        txtPrecio.setText(String.valueOf(precio));
    }//GEN-LAST:event_comboTipoPanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdRegistrarVenta;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JComboBox<String> comboTipoPan;
    private javax.swing.JComboBox<String> comboTipoSandwich;
    private javax.swing.JLabel lblCostosFijos;
    private javax.swing.JLabel lblGananciasNetas;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblIngresos;
    private javax.swing.JLabel lblJamon;
    private javax.swing.JLabel lblListaTipoPan;
    private javax.swing.JLabel lblListaTiposSandwich;
    private javax.swing.JLabel lblMortadela;
    private javax.swing.JLabel lblPanBanco;
    private javax.swing.JLabel lblPanIntegral;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblQueso;
    private javax.swing.JLabel lblRiesgos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextField txtCostosFijos;
    private javax.swing.JTextField txtGananciasNetas;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtIngresos;
    private javax.swing.JTextField txtJamon;
    private javax.swing.JTextField txtMortadela;
    private javax.swing.JTextField txtPanBlanco;
    private javax.swing.JTextField txtPanIntegral;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtQueso;
    private javax.swing.JTextField txtRiesgos;
    // End of variables declaration//GEN-END:variables

    private void actualizarGUI() {
        txtQueso.setText(String.valueOf(maquina.getCantidadQueso()));
        txtMortadela.setText(String.valueOf(maquina.getCantidadMortadela()));
        txtJamon.setText(String.valueOf(maquina.getCantidadJamon()));
        txtPanBlanco.setText(String.valueOf(maquina.getCantidadPanBlanco()));
        txtPanIntegral.setText(String.valueOf(maquina.getCantidadPanIntegral()));

        txtIngresos.setText(String.valueOf(maquina.getIngresosPorVentas()));

        txtIVA.setText(String.valueOf(maquina.getIVA()));
        txtCostosFijos.setText(String.valueOf(maquina.getCostosFijos()));
        txtRiesgos.setText(String.valueOf(maquina.getRiesgos()));
        txtGananciasNetas.setText(String.valueOf(maquina.getGananciaNeta()));
    }

    private void center() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);
        this.setLocation(x, y);
    }
}
